version: '2'
services:
    jhipste-app:
        image: jhipste
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipste-mysql:3306/jhipste?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipste-mysql:
        extends:
            file: mysql.yml
            service: jhipste-mysql
